name: Generate Snake

on:
  schedule: # Run at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: dines-04
          outputs: dist/snake.svg

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add -A
          git commit -m "Updated the snake animation" || echo "No changes to commit"
          git push
